### ISSUE TITLE
one file got error will interrupt the scan

### ISSUE THREAD

**Issue by indigofeather** [bucaran/fly-eslint#1]
Hello~

I found some problems.

Now:
![image](https://cloud.githubusercontent.com/assets/512821/9402358/2c627748-480f-11e5-9bd9-087bcbf06dd3.png)

Without `throw` (https://github.com/bucaran/fly-eslint/blob/master/index.js#L10)
I can get the whole result:

![image](https://cloud.githubusercontent.com/assets/512821/9402387/7c517f9c-480f-11e5-9fdc-d553311c6738.png)

**Comment by ghost** [comment]
Ohhh, thank you for digging in this plugin! I knew there was something weird about it, but hadn't had a chance to look at it. Do you want to send me a fix :smile:

**Comment by indigofeather** [comment]
```js
const CLIEngine = require("eslint").CLIEngine

function createLinter (cli) {
  const fmt = cli.getFormatter()
  return (file) => {
    const report = cli.executeOnFiles([file])
    const msg = fmt(report.results)
    if (msg === "") return 0
    console.error(msg)
    return parseInt(report.errorCount + report.warningCount)
  }
}

module.exports = function () {
  this.eslint = function (opts) {
    const lint = createLinter(new CLIEngine(opts))
    return this.unwrap((files) => {
      let problems = 0
      files.forEach(file => {
        problems += lint(file)
      })
      if (problems > 0) throw problems + " problems."
    })
  }
}

```

Maybe this could fix, but I don't know your coding style :smile:
