### ISSUE TITLE
Release containing newest bug fixes

### ISSUE THREAD

**Issue by marionebl** [bucaran/fly-eslint#9]
it would be amazing if you could create the patch release 0.4.1 containing the latest bug fixes.

**Comment by ghost** [comment]
My bad, I will get around this sometime tomorrow :+1:

**Comment by marionebl** [comment]
Any news on this? :trollface:

**Comment by ghost** [comment]
@marionebl Released as v1.0.

I went ahead and took the liberty to add you as a collaborator :smile:

**Comment by marionebl** [comment]
:+1: Thanks a lot, also for adding me as contrib. Cheers.
